elastic_major_version: "{{ elastic_version.split('.')[0] }}"
elastic_is_snapshot: "{{ '-SNAPSHOT' in elastic_version }}"
elastic_version_apt: "{{ elastic_version | replace('-SNAPSHOT', '~SNAPSHOT') }}"
elastic_repo_url: "https://artifacts.elastic.co/packages/{{ elastic_major_version }}.x/apt"
elastic_deb_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
elastic_artifacts_api: "https://artifacts-api.elastic.co/v1/search/{{ elastic_version }}"
